### ISSUE TITLE
2018 general results for Dauphin County has only Governors race

### ISSUE THREAD

**Issue by milandv** [openelections/openelections-data-pa#14]
Results from other offices appear to be missing.

**Comment by dwillis** [comment]
@milandv You're right - the statewide file only has governor. That's because we didn't standardize the offices in the [county file](https://github.com/openelections/openelections-data-pa/blob/master/2018/counties/20181106__pa__general__dauphin__precinct.csv). We'll do that and regenerate the statewide file.
