### ISSUE TITLE
GIS files for voting precincts?

### ISSUE THREAD

**Issue by jtotoole** [openelections/openelections-data-pa#84]
Hi all, thanks for this awesome resource! Does anyone know whether there are GIS files (e.g. .shp, .geojson) for voting district boundaries statewide, similar to what Allegheny County publishes [here](https://openac-alcogis.opendata.arcgis.com/datasets/faaf42d7eaa041cb9fa623ac7b42f475_0/data?geometry=-80.888%2C40.251%2C-79.151%2C40.617)? Something like [this](https://github.com/nvkelso/election-geodata/tree/migurski/add-pa-2016/data/42-pennsylvania/statewide) from the [election-geodata](https://github.com/nvkelso/election-geodata) project would be perfect, but their data hasn't been updated since 2017, so the boundaries are out-of-date, and the repo appears to no longer be maintained.

**Comment by rootsmusic** [comment]
Yes @jtotoole, you can filter for VEST as source at https://redistrictingdatahub.org/state/pennsylvania/

**Comment by rootsmusic** [comment]
You're welcome.  For 2020, the state has released [official voting district shapefiles](https://www.redistricting.state.pa.us/maps/#census).  VEST's shapefiles were less accurate than official sources, because they were constructed using the boundaries that had been proposed to the Census Bureau (before the boundaries were adjusted by the state specifically for the election).
